# Generated by Django 3.2.8 on 2022-02-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_estashment', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='establishment/')),
                ('logo_small', models.ImageField(blank=True, null=True, upload_to='establishment/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='establishment')),
                ('site_header', models.CharField(default='Sup-Management Mauritanie', help_text='Entete de la page Admin', max_length=100)),
                ('site_title', models.CharField(default='Sup-Management-Mauritanie', help_text='Title of our site ', max_length=80)),
                ('index_title', models.CharField(default='Sup Management Mauritanie Admin', help_text='Super Admin dashboard listing pages', max_length=100)),
                ('motto', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
